# Generated by Django 4.2.5 on 2023-10-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Title"),
                ),
                (
                    "short_description",
                    models.CharField(
                        max_length=255, verbose_name="Short description"
                    ),
                ),
                (
                    "long_description",
                    models.TextField(verbose_name="Long description"),
                ),
                ("lon", models.FloatField(verbose_name="Longitude")),
                ("lat", models.FloatField(verbose_name="Latitude")),
            ],
        ),
    ]
