# Generated by Django 4.2.5 on 2023-10-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moscow_places", "0002_alter_place_short_description"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="place",
            table="Place",
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/", verbose_name="Image"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="moscow_places.place",
                    ),
                ),
            ],
            options={
                "db_table": "Photo",
                "ordering": ["place"],
            },
        ),
    ]
