# Generated by Django 4.2.5 on 2023-10-04 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moscow_places", "0003_alter_place_table_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo",
                to="moscow_places.place",
            ),
        ),
    ]
