# Generated by Django 4.2.5 on 2023-10-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moscow_places", "0004_alter_photo_image_alter_photo_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["my_order"]},
        ),
        migrations.AddField(
            model_name="photo",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
