# Generated by Django 4.2.5 on 2023-10-07 07:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moscow_places", "0005_alter_photo_options_photo_my_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["order"]},
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="my_order",
            new_name="order",
        ),
        migrations.AlterField(
            model_name="place",
            name="long_description",
            field=tinymce.models.HTMLField(verbose_name="Long description"),
        ),
    ]
