# Generated by Django 4.2.5 on 2023-10-22 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "moscow_places",
            "0006_alter_photo_options_rename_my_order_photo_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("lon", "lat")},
        ),
    ]
